#!/usr/bin/env python

__author__ = "Zach Sailer"
__email__ = "zachsailer@gmail.com"

import argparse
from pymad import mad
from pymad import load_tree

def main(input, output, schema="newick"):
    """"""
    # Load tree from file
    tree = load_tree(input, schema=schema)

    # Run the MAD algorithm
    new_tree, Rindex = mad(tree)

    # Write out tree.
    new_tree.write(path=output, schema=schema)

    # Write score to command line.
    print(Rindex)


if __name__ == "__main__":

    # CLI handler
    parser = argparse.ArgumentParser(description="""Reroot a phylogenetic tree on branch
        with the minimal ancestor deviation.""")
    parser.add_argument("-i", type=str, help="Input tree file.")
    parser.add_argument("-o", type=str, help="Output tree file with new root.")
    parser.add_argument("--schema", default="newick", help="type of tree file (default is 'newick').")

    # Parse the arguments
    args = parser.parse_args()
    # Run the main program
    main(args.i, args.o, schema=args.schema)
